Make run smarter

diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,4 +1,12 @@
 #!/bin/sh
-bin/python ./plsc plsc.yml
-bin/python ./slp-ordered plsc.yml
-bin/python ./plsc-flat plsc.yml
+if [ -z "$1" ]; then
+  echo "No configuration given"
+  exit 1
+elif [ ! -f "$1" ]; then
+  echo "configuration not found"
+  exit 1
+fi
+
+bin/python ./plsc "$1"
+bin/python ./slp-ordered "$1"
+bin/python ./plsc-flat "$1"
